---
- name: Run shell script to change hostname
  hosts: all
  become: yes
  tasks:
    - name: Copy shell script to server
      copy:
        src: change_hostname.sh  # Update this with the path to your shell script
        dest: /tmp/change_hostname.sh         # Destination path on the server

    - name: Make script executable
      command: chmod +x /tmp/change_hostname.sh

    - name: Execute shell script
      command: /tmp/change_hostname.sh
