---
- name: Update OEL7 server
  hosts: all  # Replace with the target server(s) or server group(s)
  become: yes  # Run tasks with root privileges
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
