---
- name: Change hostname on Oracle Enterprise Linux 7
  hosts: all
  become: yes

  tasks:
    - name: Set new hostname
      command: hostnamectl set-hostname "{{ new_hostname }}"


    - name: Restarting network for changes to take effect
      service:
        name: network
        state: restarted
